import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/llm-analysis
 *
 * Serves the llm_analysis.json file generated by the scanner when
 * --llm-analyze is enabled. The analysis contains:
 *   - owasp_classifications: LLM's OWASP category for each regex finding
 *   - llm_detected_vulns: vulnerabilities the LLM found that regex missed
 *   - false_positive_candidates: regex findings the LLM thinks are FPs
 *   - follow_up_tests: suggested manual tests
 *   - summary: overall assessment
 *   - llm_error: error message if the LLM call failed
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const analysisPath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "llm_analysis.json",
  );

  try {
    const content = await fs.readFile(analysisPath, "utf-8");
    const analysis = JSON.parse(content);
    return NextResponse.json({ analysis });
  } catch {
    return NextResponse.json(
      {
        error: "LLM analysis not found",
        detail:
          "This scan did not use LLM vulnerability analysis, or the analysis file hasn't been generated yet (it runs after active scanning completes).",
      },
      { status: 404 },
    );
  }
}
