import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/llm-plan
 *
 * Serves the llm_plan.json file generated by the scanner when --llm-assist
 * is enabled. The plan contains:
 *   - priority_inputs: string[]  (input names to test first)
 *   - custom_payloads: string[]  (extra payloads the LLM suggested)
 *   - additional_urls: string[]  (URLs the LLM suggested crawling)
 *   - reasoning: string          (LLM's explanation)
 *   - llm_error: string | null   (populated if the LLM call failed)
 *
 * Returns 404 if the scan didn't use --llm-assist or the plan file doesn't
 * exist yet (scan still running or not started).
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const planPath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "llm_plan.json",
  );

  try {
    const content = await fs.readFile(planPath, "utf-8");
    const plan = JSON.parse(content);
    return NextResponse.json({ plan });
  } catch {
    return NextResponse.json(
      {
        error: "LLM plan not found",
        detail:
          "This scan did not use LLM-assisted scanning, or the plan file hasn't been generated yet (the LLM planner runs after crawling completes).",
      },
      { status: 404 },
    );
  }
}
