import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/findings
 *
 * Serves the findings.json file generated by the scanner. Contains all
 * active findings (XSS, SQLi, Broken Access Control) with full details:
 *   - finding_id, owasp_category, title, severity
 *   - url, payload, patterns_matched
 *   - request_raw, response_raw
 *   - execution_trail (steps to reproduce)
 *   - screenshot_path, has_screenshot
 *   - unverified (always true)
 *
 * Used by the interactive OWASP tab to show findings grouped by category.
 *
 * OWASP CATEGORY NORMALISATION:
 * Older scans (pre-2025 OWASP update) wrote categories like
 * "A03 Injection" or "A03:2021 Injection". The current UI filters on
 * "A05:2025 Injection" (and a fallback of "A05 Injection"). Without
 * normalisation, findings from old scans vanish from the OWASP tab
 * because no 2025 category matches. We rewrite legacy strings to their
 * 2025 equivalents on read so the UI Just Works regardless of when the
 * scan was produced.
 */

// Legacy → OWASP 2025 mapping. Keys are case-insensitive.
const OWASP_2025_NORMALISATION: Record<string, string> = {
  // OWASP 2021 → 2025 renumbering
  "a01 injection": "A05:2025 Injection",
  "a01:2021 injection": "A05:2025 Injection",
  "a03 injection": "A05:2025 Injection",
  "a03:2021 injection": "A05:2025 Injection",
  "a04 xxl": "A05:2025 Injection", // 2021 A04 was "Insecure Design" actually; XXE was 2017
  "a06 misconfig": "A02:2025 Security Misconfiguration",
  "a06:2021 misconfig": "A02:2025 Security Misconfiguration",
  "a02 crypto": "A04:2025 Cryptographic Failures",
  "a02:2021 crypto": "A04:2025 Cryptographic Failures",
  "a02 cryptographic failures": "A04:2025 Cryptographic Failures",
  "a02:2021 cryptographic failures": "A04:2025 Cryptographic Failures",
  "a07 auth": "A07:2025 Identification and Authentication Failures",
  "a07:2021 auth": "A07:2025 Identification and Authentication Failures",
  "a07 authentication failures": "A07:2025 Identification and Authentication Failures",
  "a07:2021 authentication failures": "A07:2025 Identification and Authentication Failures",
  "a08 data integrity": "A08:2025 Software and Data Integrity Failures",
  "a08:2021 data integrity": "A08:2025 Software and Data Integrity Failures",
  "a09 logging": "A09:2025 Security Logging and Monitoring Failures",
  "a09:2021 logging": "A09:2025 Security Logging and Monitoring Failures",
  "a10 ssrf": "A10:2025 Server-Side Request Forgery",
  "a10:2021 ssrf": "A10:2025 Server-Side Request Forgery",

  // Bare "A05 Injection" (without :2025) → canonical form
  "a05 injection": "A05:2025 Injection",
  "a01 broken access control": "A01:2025 Broken Access Control",
  "a02 security misconfiguration": "A02:2025 Security Misconfiguration",
  "a04 cryptographic failures": "A04:2025 Cryptographic Failures",
  "a06 insecure design": "A06:2025 Insecure Design",
  "a07 identification and authentication failures": "A07:2025 Identification and Authentication Failures",
  "a08 software and data integrity failures": "A08:2025 Software and Data Integrity Failures",
  "a09 security logging and monitoring failures": "A09:2025 Security Logging and Monitoring Failures",
  "a10 server-side request forgery": "A10:2025 Server-Side Request Forgery",

  // "Uncategorized" stays as-is.
};

// The valid OWASP 2025 categories the UI knows. Used by the label-fallback
// in normaliseOwaspCategory to fix LLM mistakes (wrong number, right label).
const OWASP_2025_VALID = [
  "A01:2025 Broken Access Control",
  "A02:2025 Security Misconfiguration",
  "A03:2025 Software Supply Chain Failures",
  "A04:2025 Cryptographic Failures",
  "A05:2025 Injection",
  "A06:2025 Insecure Design",
  "A07:2025 Identification and Authentication Failures",
  "A08:2025 Software or Data Integrity Failures",
  "A09:2025 Security Logging and Monitoring Failures",
  "A10:2025 Mishandling of Exceptional Conditions",
];

// LLM labels that don't match any valid category label → alias to the
// closest valid one. (e.g. the LLM often says "Cross-Site Scripting" which
// doesn't exist as a 2025 category — XSS is under Injection.)
const OWASP_LABEL_ALIASES: Record<string, string> = {
  "cross-site scripting": "A05:2025 Injection",
  "xss": "A05:2025 Injection",
  "sql injection": "A05:2025 Injection",
  "sqli": "A05:2025 Injection",
  "ssrf": "A05:2025 Injection",
  "server-side request forgery": "A05:2025 Injection",
  "broken authentication": "A07:2025 Identification and Authentication Failures",
  "cryptographic failures": "A04:2025 Cryptographic Failures",
  "crypto": "A04:2025 Cryptographic Failures",
  "sensitive data exposure": "A04:2025 Cryptographic Failures",
  "security misconfiguration": "A02:2025 Security Misconfiguration",
  "misconfiguration": "A02:2025 Security Misconfiguration",
};

function normaliseOwaspCategory(raw: unknown): string | undefined {
  if (typeof raw !== "string" || raw.length === 0) return undefined;
  const key = raw.toLowerCase().trim();
  // 1. Explicit map (legacy → 2025 renumbering).
  if (OWASP_2025_NORMALISATION[key]) {
    return OWASP_2025_NORMALISATION[key];
  }
  // 2. Exact match to a valid 2025 category (case-insensitive).
  for (const v of OWASP_2025_VALID) {
    if (v.toLowerCase() === key) return v;
  }
  // 3. LABEL FALLBACK: the LLM often gets the NUMBER wrong but the LABEL
  //    right (e.g. "A05:2025 Security Misconfiguration" — A05 is Injection,
  //    not Security Misconfig). Strip the A##:20## prefix and match by label.
  const prefixMatch = key.match(/^a\d{2}:\d{4}\s+(.+)$/);
  const label = prefixMatch ? prefixMatch[1] : key;
  for (const v of OWASP_2025_VALID) {
    const vLabel = v.toLowerCase().replace(/^a\d{2}:\d{4}\s+/, "");
    if (vLabel === label) return v;
  }
  // 4. Label alias (labels that don't exist as categories — e.g. "xss").
  if (OWASP_LABEL_ALIASES[label]) return OWASP_LABEL_ALIASES[label];
  // 5. Unknown — return as-is (don't silently drop).
  return raw;
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "findings.json",
  );

  try {
    const content = await fs.readFile(filePath, "utf-8");
    let findings = JSON.parse(content);

    // DEDUPLICATE by finding_id. Across supervisor restarts / Kill-Chrome &
    // Restart / --resume, the same finding can occasionally end up in
    // findings.json more than once (the incremental writes + scan_state
    // reloads can race). Duplicate ids cause React key collisions in the
    // OWASP tab ("two children with the same key"). We keep the FIRST
    // occurrence of each id and drop later duplicates. This is the single
    // chokepoint that guarantees the UI never sees dupes regardless of how
    // they got into the file (old scans on disk included).
    if (Array.isArray(findings)) {
      const seen = new Set<string>();
      findings = findings.filter((f: unknown) => {
        if (!f || typeof f !== "object") return true;
        const fid = (f as Record<string, unknown>).finding_id;
        if (typeof fid !== "string" || fid.length === 0) return true;
        if (seen.has(fid)) return false; // duplicate id — drop
        seen.add(fid);
        return true;
      });
    }

    // Normalise legacy OWASP category strings to their 2025 equivalents
    // so the UI's category filter (which only knows 2025 strings) shows
    // findings from old scans too.
    if (Array.isArray(findings)) {
      for (const f of findings) {
        if (f && typeof f === "object") {
          const normalised = normaliseOwaspCategory(
            (f as Record<string, unknown>).owasp_category,
          );
          if (normalised) {
            (f as Record<string, unknown>).owasp_category = normalised;
          }
        }
      }
    }

    // --- Merge Interesting Locations into the findings as Info-severity
    //     items under the appropriate OWASP category. This puts everything
    //     security-relevant in one place (the OWASP tab) — active-test
    //     findings + heuristic flags (admin panels, IDOR candidates, SSRF
    //     candidates, etc.) side by side. ---
    try {
      const ilPath = path.join(
        process.cwd(), "scan-output", id, "interesting_locations.json",
      );
      const ilRaw = await fs.readFile(ilPath, "utf-8");
      const il = JSON.parse(ilRaw);
      const ilMap: Record<string, string> = {
        // Param categories → OWASP
        "idor candidate": "A01:2025 Broken Access Control",
        "open redirect candidate": "A01:2025 Broken Access Control",
        "path traversal / lfi candidate": "A01:2025 Broken Access Control",
        "sql injection candidate": "A05:2025 Injection",
        "command injection candidate": "A05:2025 Injection",
        "xss candidate": "A05:2025 Injection",
        "ssrf candidate": "A05:2025 Injection",
        "sensitive parameter": "A02:2025 Security Misconfiguration",
        // URL categories
        "admin panel": "A02:2025 Security Misconfiguration",
        "config endpoint": "A02:2025 Security Misconfiguration",
        "debug endpoint": "A02:2025 Security Misconfiguration",
        "version control exposure": "A02:2025 Security Misconfiguration",
        "environment file": "A02:2025 Security Misconfiguration",
        "backup directory": "A02:2025 Security Misconfiguration",
        "api endpoint": "A06:2025 Insecure Design",
        "rest api": "A06:2025 Insecure Design",
        "soap api": "A06:2025 Insecure Design",
        "graphql endpoint": "A06:2025 Insecure Design",
        "file upload": "A05:2025 Injection",
        "file download": "A05:2025 Injection",
        "file endpoint": "A05:2025 Injection",
        "data import/export": "A05:2025 Injection",
        "webhook/callback": "A05:2025 Injection",
        // Header categories
        "server banner (info disclosure)": "A02:2025 Security Misconfiguration",
        "framework banner (info disclosure)": "A02:2025 Security Misconfiguration",
        "asp.net version (info disclosure)": "A02:2025 Security Misconfiguration",
        "debug header": "A02:2025 Security Misconfiguration",
      };
      let ilIdx = 0;
      for (const listKey of ["url_findings", "param_findings", "header_findings"]) {
        const list = il[listKey];
        if (!Array.isArray(list)) continue;
        for (const entry of list) {
          if (!entry || typeof entry !== "object") continue;
          const cat = String((entry as Record<string, unknown>).category || "").toLowerCase();
          const owasp = ilMap[cat] || "A05:2025 Injection";
          const url = String((entry as Record<string, unknown>).url || "") ||
                      String((entry as Record<string, unknown>).header || "");
          const param = (entry as Record<string, unknown>).param_name;
          const title = param
            ? `${(entry as Record<string, unknown>).category}: '${param}' in ${url}`
            : `${(entry as Record<string, unknown>).category}: ${url}`;
          if (!Array.isArray(findings)) findings = [];
          (findings as unknown[]).push({
            finding_id: `il_${listKey}_${ilIdx++}`,
            owasp_category: owasp,
            title,
            severity: "Info",
            url,
            payload: "",
            patterns_matched: ["InterestingLocation"],
            execution_trail: [],
            unverified: true,
            interesting_location: true,
            description: (entry as Record<string, unknown>).description || "",
          });
        }
      }
    } catch {
      // No interesting_locations.json — skip silently.
    }

    return NextResponse.json({ findings });
  } catch {
    return NextResponse.json(
      {
        error: "Findings not found",
        detail:
          "The findings.json file hasn't been generated yet. It's written after active scanning + access control testing complete.",
        findings: [],
      },
      { status: 404 },
    );
  }
}
