import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/ssl
 *
 * Serves the ssl_record.json file generated by the scanner during the
 * SSL/TLS inspection phase.
 *
 * Contains:
 *   - hostname, port
 *   - issuer, subject
 *   - not_before, not_after, days_until_expiry
 *   - is_expired, is_self_signed, is_untrusted_root, hostname_mismatch
 *   - negotiated_cipher, negotiated_protocol
 *   - weak_ciphers_detected, weak_protocols_detected
 *   - pem_chain (full certificate chain in PEM format)
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "ssl_record.json",
  );

  try {
    const content = await fs.readFile(filePath, "utf-8");
    const ssl = JSON.parse(content);
    return NextResponse.json({ ssl });
  } catch {
    return NextResponse.json(
      {
        error: "SSL record not found",
        detail:
          "The ssl_record.json file hasn't been generated yet. " +
          "It's created during the SSL/TLS inspection phase (only for HTTPS targets).",
        ssl: null,
      },
      { status: 404 },
    );
  }
}
