import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/passive
 *
 * Serves the passive_findings.json file generated by the scanner.
 *
 * Contains:
 *   - missing_security_headers: string[]
 *   - insecure_cookies: array of {name, domain, path, issues}
 *   - mixed_content: array of {tag, url, attr}
 *   - error_messages: array of {category, severity, snippet, owasp}
 *   - session_cookie_config: array of {name, domain, path, expires, issues, owasp}
 *   - sensitive_info: array of {category, severity, value, owasp}
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(), "scan-output", id, "passive_findings.json",
  );

  try {
    const content = await fs.readFile(filePath, "utf-8");
    const data = JSON.parse(content);
    return NextResponse.json({ passive: data });
  } catch {
    return NextResponse.json(
      {
        error: "Passive findings not found",
        detail: "The passive_findings.json file hasn't been generated yet.",
        passive: null,
      },
      { status: 404 },
    );
  }
}
