import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";
import { DEFAULT_WHITELIST_PATH } from "@/lib/scanner-paths";

/**
 * GET /api/scans/[id]/headers
 *
 * Serves the headers_comparison.json file generated by the scanner.
 * Contains HeaderRecord objects with:
 *   - name: header name
 *   - value: actual header value
 *   - in_reference: boolean (was this header in the whitelist?)
 *   - expected_value: string (expected value from whitelist, "" if none)
 *   - value_matches_expected: boolean (does actual match expected?)
 *
 * Also computes "missing_headers" — headers that are in the whitelist
 * but were NOT found in the captured response. These are potential
 * security misconfigurations (e.g. missing Strict-Transport-Security).
 *
 * Used by the "Headers" sub-tab to render:
 *   - Table A: all captured headers with comparison
 *   - Table B: anomalies (not in whitelist)
 *   - Table C: policy violations (in whitelist but value mismatch)
 *   - Table D: missing headers (in whitelist but not in response)
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "headers_comparison.json",
  );

  let headers: any[] = [];
  try {
    const content = await fs.readFile(filePath, "utf-8");
    headers = JSON.parse(content);
  } catch {
    return NextResponse.json(
      {
        error: "Header comparison not found",
        detail:
          "The headers_comparison.json file hasn't been generated yet. It's created during the header capture phase (early in the scan).",
        headers: [],
        missing_headers: [],
      },
      { status: 404 },
    );
  }

  // --- Compute missing headers ---
  // Read the PER-SCAN whitelist (from the scan's output directory) and
  // find headers that are expected but NOT present in the captured response.
  // Fall back to the default whitelist if the per-scan copy doesn't exist.
  let missing_headers: Array<{ name: string; expected_value: string }> = [];
  try {
    // Try the per-scan whitelist first (this is what the scanner actually used)
    const perScanWhitelistPath = path.join(
      process.cwd(), "scan-output", id, "whitelist.txt",
    );
    let whitelistContent: string;
    try {
      whitelistContent = await fs.readFile(perScanWhitelistPath, "utf-8");
    } catch {
      // Fall back to the default whitelist
      whitelistContent = await fs.readFile(DEFAULT_WHITELIST_PATH, "utf-8");
    }
    // Parse the whitelist: one header per line, format "Name" or "Name: value"
    const expectedHeaders = new Map<string, string>(); // lowercased name → expected value
    for (const line of whitelistContent.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const colonIdx = trimmed.indexOf(":");
      if (colonIdx === -1) {
        // Format: "Header-Name" (no expected value)
        // Only set if not already in the map (don't overwrite a
        // previous entry that had an expected value)
        const key = trimmed.toLowerCase();
        if (!expectedHeaders.has(key)) {
          expectedHeaders.set(key, "");
        }
      } else {
        const name = trimmed.slice(0, colonIdx).trim();
        const value = trimmed.slice(colonIdx + 1).trim();
        const key = name.toLowerCase();
        // Always overwrite with the value-bearing entry (a header
        // that appears twice — once with value, once without — should
        // use the one with the value for policy enforcement)
        expectedHeaders.set(key, value);
      }
    }

    // Build a set of captured header names (lowercased)
    const capturedNames = new Set(headers.map((h: any) => h.name.toLowerCase()));

    // Find missing: in whitelist but NOT in captured
    for (const [name, expectedValue] of expectedHeaders) {
      if (!capturedNames.has(name)) {
        missing_headers.push({ name, expected_value: expectedValue });
      }
    }
  } catch {
    // Whitelist file not found — skip missing headers computation.
  }

  return NextResponse.json({ headers, missing_headers });
}
