import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/file-uploads
 *
 * Serves the file_uploads.json file generated by the scanner when
 * --test-file-upload is enabled. Contains one row per upload probe attempt
 * (accepted AND rejected), each with:
 *   - probe_id, filename, mime_sent, content_desc
 *   - input_url, input_name, http_status
 *   - accepted, filename_reflected
 *   - landing_urls[]   (URLs/paths reflected in the response — strongest)
 *   - candidate_urls[] (best-effort guesses under /uploads/, /files/, etc.)
 *   - response_preview, screenshot, severity, owasp, rationale
 *
 * The Uploads tab renders this as a table; landing/candidate URLs are
 * clickable so the engineer can manually verify whether the file is served.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "file_uploads.json",
  );

  try {
    const content = await fs.readFile(filePath, "utf-8");
    const uploads = JSON.parse(content);
    return NextResponse.json({ uploads });
  } catch {
    return NextResponse.json(
      {
        error: "File-upload findings not found",
        detail:
          "This scan did not use --test-file-upload, no <input type=file> was discovered, or the file hasn't been generated yet.",
        uploads: [],
      },
      { status: 404 },
    );
  }
}
