import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/deep-logic
 *
 * Serves the deep_logic_findings.json file generated by the scanner when
 * --deep-logic is enabled. Contains business logic findings with:
 *   - title, severity, owasp_category (A04 Insecure Design)
 *   - happy_path, mutation_applied, anomaly
 *   - baseline_snippet, mutated_snippet
 *   - execution_trail (steps to reproduce)
 *   - screenshot_path, has_screenshot
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "deep_logic_findings.json",
  );

  try {
    const content = await fs.readFile(filePath, "utf-8");
    const findings = JSON.parse(content);
    return NextResponse.json({ findings });
  } catch {
    return NextResponse.json(
      {
        error: "Deep logic findings not found",
        detail:
          "This scan did not use --deep-logic, or the findings file hasn't been generated yet.",
        findings: [],
      },
      { status: 404 },
    );
  }
}
