import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/interesting-locations
 *
 * Serves the interesting_locations.json file generated by the scanner
 * after attack surface mapping. Contains:
 *   - url_findings: high-value URLs (admin, api, auth, file ops)
 *   - param_findings: high-value parameters (id, redirect, cmd, file, etc.)
 *   - header_findings: info-disclosure headers (Server, X-Powered-By)
 *   - summary: category counts
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "interesting_locations.json",
  );

  try {
    const content = await fs.readFile(filePath, "utf-8");
    const data = JSON.parse(content);
    return NextResponse.json({ locations: data });
  } catch {
    return NextResponse.json(
      {
        error: "Interesting locations not found",
        detail:
          "This file is generated after attack surface mapping completes. If the scan is still running, check back shortly.",
      },
      { status: 404 },
    );
  }
}
