import { NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

/**
 * GET /api/scans/[id]/crawl-map
 *
 * Returns the crawl_map.json file generated by the scanner.
 * Contains all crawled URLs with their depth, source, and scope status.
 */
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const filePath = path.join(
    process.cwd(),
    "scan-output",
    id,
    "crawl_map.json",
  );

  try {
    const content = await fs.readFile(filePath, "utf-8");
    const crawlMap = JSON.parse(content);
    return NextResponse.json({ crawlMap });
  } catch {
    return NextResponse.json(
      { error: "Crawl map not found", crawlMap: [] },
      { status: 404 },
    );
  }
}
